CREATE DATABASE ceni;

CREATE USER ceni_manager WITH PASSWORD '123456';
GRANT ALL PRIVILEGES ON DATABASE ceni TO ceni_manager;

\c ceni

GRANT ALL ON SCHEMA public TO ceni_manager;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ceni_manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ceni_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO ceni_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO ceni_manager;
